# Generated by Django 4.2.18 on 2025-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialorganizationnews',
            name='source_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='financialorganizationnews',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
