# Generated by Django 4.2.18 on 2025-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_financialorganizationnews_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialorganizationnews',
            name='source_url',
            field=models.URLField(verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='financialorganizationnews',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
