# Generated by Django 4.2.18 on 2025-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialorganization',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='phone',
            field=models.CharField(default='Not provided', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='status',
            field=models.CharField(default='Active', max_length=50, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='license_number',
            field=models.CharField(max_length=100, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
