# Generated by Django 4.2.18 on 2025-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_financialorganization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialorganization',
            name='bin_iin',
            field=models.CharField(default='000000000000', max_length=12, unique=True, verbose_name='БИН/ИИН'),
        ),
    ]
