# Generated by Django 4.2.18 on 2025-01-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_financialorganization_bin_iin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganizationNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('source_url', models.URLField(verbose_name='Ссылка на источник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_news', to='organizations.financialorganization', verbose_name='Организация')),
            ],
        ),
    ]
