# Generated by Django 4.2.18 on 2025-01-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_financialorganizationnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialOrganizationNews',
        ),
    ]
