# Generated by Django 4.2.18 on 2025-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_delete_financialorganizationnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialorganization',
            name='website',
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='bin_iin',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='БИН/ИИН'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
