# Generated by Django 4.2.18 on 2025-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_financialorganization_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialorganization',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
